; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = "AAA PDN"
default_envs = esp32-s3_pdn_release
extra_configs = wifi_credentials.ini

[env:esp32-s3_base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-n8r8
board_build.arduino.memory_type = dio_opi
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, send_on_enter
monitor_echo = yes
monitor_dtr = 0
monitor_rts = 0
board_build.partitions = partitions.csv
build_src_filter = 
	+<*>
	-<cli/*>
	-<fdn/*>
build_flags = 
	-DBOARD_HAS_PSRAM
	'-DWIFI_SSID="${wifi.WIFI_SSID}"'
	'-DWIFI_PASSWORD="${wifi.WIFI_PASSWORD}"'
	'-DBASE_URL="${wifi.BASE_URL}"'
	-I src/pdn
lib_deps = 
	olikraus/U8g2@^2.35.14
	fastled/FastLED@^3.6.0
	mathertel/OneButton@^2.5.0
	ArduinoJson@^7.4.2
	WiFi
	nanopb/Nanopb@^0.4.92
extra_scripts = 
	pre:scripts/firmware_commit_hash.py
	scripts/multi_flash_target.py
	scripts/auto_compiledb.py
custom_multi_flash_args = 

[env:esp32-s3_pdn_debug]
extends = env:esp32-s3_base
build_type = debug
build_flags = 
	${env:esp32-s3_base.build_flags}
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_MODE=1
debug_tool = esp-builtin
debug_init_break = tbreak loop

[env:esp32-s3_pdn_release]
extends = env:esp32-s3_base
build_type = release
build_flags = 
	${env:esp32-s3_base.build_flags}
	-DCORE_DEBUG_LEVEL=2
custom_multi_flash_args = --clear-nvs

[env:esp32-s3_pdn_release_verbose]
extends = env:esp32-s3_base
build_type = release
build_flags = 
	${env:esp32-s3_base.build_flags}
	-DCORE_DEBUG_LEVEL=5

[env:esp32-s3_fdn_base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-n8r8
board_build.arduino.memory_type = dio_opi
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, send_on_enter
monitor_echo = yes
monitor_dtr = 0
monitor_rts = 0
board_build.partitions = partitions.csv
build_src_filter = 
	+<*>
	-<cli/*>
	-<pdn/*>
build_flags = 
	-DBOARD_HAS_PSRAM
	'-DWIFI_SSID="${wifi.WIFI_SSID}"'
	'-DWIFI_PASSWORD="${wifi.WIFI_PASSWORD}"'
	'-DBASE_URL="${wifi.BASE_URL}"'
	-I src/fdn
lib_deps = 
	olikraus/U8g2@^2.35.14
	fastled/FastLED@^3.6.0
	mathertel/OneButton@^2.5.0
	ArduinoJson@^7.4.2
	WiFi
	nanopb/Nanopb@^0.4.92
extra_scripts = 
	pre:scripts/firmware_commit_hash.py
	scripts/multi_flash_target.py
	scripts/auto_compiledb.py
custom_multi_flash_args = 

[env:esp32-s3_fdn_debug]
extends = env:esp32-s3_fdn_base
build_type = debug
build_flags = 
	${env:esp32-s3_fdn_base.build_flags}
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_MODE=1
debug_tool = esp-builtin
debug_init_break = tbreak loop

[env:esp32-s3_fdn_release]
extends = env:esp32-s3_fdn_base
build_type = release
build_flags = 
	${env:esp32-s3_fdn_base.build_flags}
	-DCORE_DEBUG_LEVEL=2
custom_multi_flash_args = --clear-nvs

[env:esp32-s3_fdn_release_verbose]
extends = env:esp32-s3_fdn_base
build_type = release
build_flags = 
	${env:esp32-s3_fdn_base.build_flags}
	-DCORE_DEBUG_LEVEL=5

[env:native]
platform = native
build_type = test
test_framework = googletest
test_build_src = yes
test_filter = test_core
extra_scripts = scripts/auto_compiledb.py
build_flags = 
	-std=c++17
	-DNATIVE_BUILD
	-I src/pdn
	-I src
build_src_filter = 
	+<*>
	-<pdn/main.cpp>
	-<fdn/*>
	-<cli/*>
lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	nanopb/Nanopb@^0.4.92
build_unflags = -Werror

[env:native_tsan]
extends = env:native
build_flags = 
	-std=c++17
	-DNATIVE_BUILD
	-I src/pdn
	-I src
	-fsanitize=thread
	-fno-omit-frame-pointer
	-g
	-O1
build_unflags = -Werror
lib_deps = nanopb/Nanopb@^0.4.92

[env:native_asan]
extends = env:native
build_flags = 
	-std=c++17
	-DNATIVE_BUILD
	-I src/pdn
	-I src
	-fsanitize=address,leak
	-fno-omit-frame-pointer
	-g
	-O1
build_unflags = -Werror
lib_deps = nanopb/Nanopb@^0.4.92

[env:native_profile]
extends = env:native
build_flags = 
	-std=c++17
	-DNATIVE_BUILD
	-I src/pdn
	-I src
	-g
	-O2
	-fno-omit-frame-pointer
build_unflags = -Werror
lib_deps = nanopb/Nanopb@^0.4.92

[env:native_perf]
platform = native
build_type = release
build_flags = 
	-std=c++17
	-DNATIVE_BUILD
	-DPERF_BUILD
	-DCORE_DEBUG_LEVEL=0
	-I src/pdn
	-I src
	-g
	-O2
	-fno-omit-frame-pointer
build_src_filter = 
	+<*>
	-<pdn/main.cpp>
	-<fdn/*>
	-<cli/cli-main.cpp>
lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	nanopb/Nanopb@^0.4.92
build_unflags = -Werror

[env:native_cli]
platform = native
build_type = release
extra_scripts = scripts/auto_compiledb.py
build_flags = 
	-std=c++17
	-DNATIVE_BUILD
	-I src/pdn
	-I src
	-pthread
build_src_filter = 
	+<*>
	-<pdn/main.cpp>
	-<fdn/*>
	-<cli/perf-main.cpp>
lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	nanopb/Nanopb@^0.4.92
build_unflags = -Werror

[env:native_cli_test]
platform = native
build_type = test
test_framework = googletest
test_build_src = yes
test_filter = test_cli
extra_scripts = scripts/auto_compiledb.py
build_flags = 
	-std=c++17
	-DNATIVE_BUILD
	-I src/pdn
	-I src
	-pthread
build_src_filter = 
	+<*>
	-<pdn/main.cpp>
	-<fdn/*>
	-<cli/*>
lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	nanopb/Nanopb@^0.4.92
build_unflags = -Werror

[wifi]
wifi_ssid = The Lab
wifi_password = C00KIECAT
base_url = https://alleycat-dl83g.ondigitalocean.app
