/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_ALLEYCAT_DEVICE_DEVICE_API_PB_H_INCLUDED
#define PB_ALLEYCAT_DEVICE_DEVICE_API_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Request body for POST /device-logs.

 The server generates:
 - id
 - received_at */
typedef struct _alleycat_device_WriteDeviceLogRequest {
    /* Colon-separated 48-bit address, such as "aa:bb:cc:dd:ee:ff". */
    bool has_device_mac;
    char device_mac[18];
    /* Device-assigned crash report number. */
    bool has_crash_number;
    uint64_t crash_number;
    /* Milliseconds since the device booted\ */
    bool has_uptime_ms;
    uint64_t uptime_ms;
    /* Firmware/software build identifier. */
    bool has_software_version;
    char software_version[16];
    /* Raw numeric reset-reason code reported by the device. */
    bool has_reset_reason;
    uint32_t reset_reason;
    /* Address of the instruction being executed when the exception occurred. */
    bool has_program_counter;
    uint32_t program_counter;
    /* Raw numeric exception-cause code. */
    bool has_exception_cause;
    uint32_t exception_cause;
    /* FreeRTOS task active when the exception occurred. */
    bool has_task_name;
    char task_name[16];
} alleycat_device_WriteDeviceLogRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define alleycat_device_WriteDeviceLogRequest_init_default {false, "", false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, ""}
#define alleycat_device_WriteDeviceLogRequest_init_zero {false, "", false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define alleycat_device_WriteDeviceLogRequest_device_mac_tag 1
#define alleycat_device_WriteDeviceLogRequest_crash_number_tag 2
#define alleycat_device_WriteDeviceLogRequest_uptime_ms_tag 3
#define alleycat_device_WriteDeviceLogRequest_software_version_tag 4
#define alleycat_device_WriteDeviceLogRequest_reset_reason_tag 5
#define alleycat_device_WriteDeviceLogRequest_program_counter_tag 6
#define alleycat_device_WriteDeviceLogRequest_exception_cause_tag 7
#define alleycat_device_WriteDeviceLogRequest_task_name_tag 8

/* Struct field encoding specification for nanopb */
#define alleycat_device_WriteDeviceLogRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   device_mac,        1) \
X(a, STATIC,   OPTIONAL, UINT64,   crash_number,      2) \
X(a, STATIC,   OPTIONAL, UINT64,   uptime_ms,         3) \
X(a, STATIC,   OPTIONAL, STRING,   software_version,   4) \
X(a, STATIC,   OPTIONAL, UINT32,   reset_reason,      5) \
X(a, STATIC,   OPTIONAL, FIXED32,  program_counter,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   exception_cause,   7) \
X(a, STATIC,   OPTIONAL, STRING,   task_name,         8)
#define alleycat_device_WriteDeviceLogRequest_CALLBACK NULL
#define alleycat_device_WriteDeviceLogRequest_DEFAULT NULL

extern const pb_msgdesc_t alleycat_device_WriteDeviceLogRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define alleycat_device_WriteDeviceLogRequest_fields &alleycat_device_WriteDeviceLogRequest_msg

/* Maximum encoded size of messages (where known) */
#define ALLEYCAT_DEVICE_DEVICE_API_PB_H_MAX_SIZE alleycat_device_WriteDeviceLogRequest_size
#define alleycat_device_WriteDeviceLogRequest_size 92

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
