/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.2 */

#include "device_api.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(alleycat_device_WriteDeviceLogRequest, alleycat_device_WriteDeviceLogRequest, AUTO)



